---
kind: Service
apiVersion: v1
metadata:
  name: "gateway"
spec:
  selector:
    app: "gateway-service"
    role: "gateway"
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 31000
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: gateway
        app: gateway-service
        track: stable
    spec:
      containers:
        - name: gateway-service
          image: "seanyinx/acmeair-webapp:2.0.0-SNAPSHOT"
          env:
            - name: JAVA_OPTS
              value: "-Dspring.profiles.active=consul -Dspring.cloud.consul.host=consul-0.consul"
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 0.2
              memory: "1Gi"
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 8080
#              scheme: HTTP
#            initialDelaySeconds: 35
#            periodSeconds: 15
#            timeoutSeconds: 5
#          readinessProbe:
#            httpGet:
#              path: /health
#              port: 8080
#              scheme: HTTP
#            initialDelaySeconds: 30
#            timeoutSeconds: 2
